title: Make Emacs Awesome Blog
logo: /assets/img/MakeEmacsAwesomeCover.png
description: Learn how to harness the power of the most versatile coding tool on the planet.
link: makeemacsawesome.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
